from typing import Protocol

class LifecycleProtocol(Protocol):
    async def initialize(self) -> None: ...
    async def dispose(self) -> None: ...

def lifecycle(cls: type[LifecycleProtocol]) -> type[LifecycleProtocol]: ...
